import {
  DARK_LEVELS,
  DARK_SURFACE,
  LIGHT_LEVELS,
  LIGHT_SURFACE,
  type Oklch,
  type Surface,
} from "@squares/domain/palette";

/**
 * The palette as CSS custom properties.
 *
 * The ramp has three consumers — these properties, the Share Card's canvas, and
 * the phone app's style values — so it has one definition, in
 * `@squares/domain/palette`, and this renders it. `tokens.css` is the committed
 * output; `palette.test.ts` asserts the two agree, so the file on disk cannot be
 * edited into disagreeing with the source it came from.
 *
 * The surface colours joined it when the phone app grew Screens. They used to
 * be written out by hand below the `@import` in `globals.css`, which was fine
 * while a stylesheet was the only thing that read them and wrong the moment
 * React Native — which cannot read a stylesheet at all — needed the same
 * twenty values.
 */
/** Trailing zeroes would differ from what the stylesheet used to say by hand. */
const num = (value: number) => String(Number(value.toFixed(4)));

const colour = ({ l, c, h, a }: Oklch) =>
  `oklch(${num(l)} ${num(c)} ${num(h)}${a === undefined ? "" : ` / ${num(a)}`})`;

const ramp = (levels: readonly Oklch[]) =>
  levels.map((level, index) => `  --lv${index}: ${colour(level)};`).join("\n");

/** `surfaceOn` is `--surface-on`: the key is the name, so there is no second list. */
const kebab = (key: string) => key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);

const surface = (tokens: Surface) =>
  Object.entries(tokens)
    .map(([key, value]) => `  --${kebab(key)}: ${colour(value)};`)
    .join("\n");

export function tokensCss(): string {
  return `/*
 * Generated by scripts/generate-tokens.mts from @squares/domain/palette.
 * Do not edit: change the palette there and run \`pnpm tokens\`.
 *
 * Why the ramp is what it is — lightness carrying the data, hue as the second
 * cue — is explained in globals.css, beside the type scale.
 */
:root,
:root[data-theme="dark"] {
${ramp(DARK_LEVELS)}

${surface(DARK_SURFACE)}
}

:root[data-theme="light"] {
${ramp(LIGHT_LEVELS)}

${surface(LIGHT_SURFACE)}
}
`;
}
