import { DARK_LEVELS, LIGHT_LEVELS, type Oklch } from "@squares/domain/palette";

/**
 * The Intensity ramp as CSS custom properties.
 *
 * The ramp has three consumers — these properties, the Share Card's canvas, and
 * the phone app's style values — so it has one definition, in
 * `@squares/domain/palette`, and this renders it. `tokens.css` is the committed
 * output; `palette.test.ts` asserts the two agree, so the file on disk cannot be
 * edited into disagreeing with the source it came from.
 */
/** Trailing zeroes would differ from what the stylesheet used to say by hand. */
const num = (value: number) => String(Number(value.toFixed(4)));

const ramp = (levels: readonly Oklch[]) =>
  levels
    .map((level, index) => `  --lv${index}: oklch(${num(level.l)} ${num(level.c)} ${num(level.h)});`)
    .join("\n");

export function tokensCss(): string {
  return `/*
 * Generated by scripts/generate-tokens.mts from @squares/domain/palette.
 * Do not edit: change the ramp there and run \`pnpm tokens\`.
 *
 * Why the ramp is what it is — lightness carrying the data, hue as the second
 * cue — is explained in globals.css, beside the rest of the palette.
 */
:root,
:root[data-theme="dark"] {
${ramp(DARK_LEVELS)}
}

:root[data-theme="light"] {
${ramp(LIGHT_LEVELS)}
}
`;
}
